POST http://localhost:5000/api/wilder/2/skill/2/grade
Content-Type: application/json

{
  "rate": 10
}

###
GET http://localhost:5000/api/wilder/1/skill/1/grade

###
PUT http://localhost:5000/api/grade/4/update
Content-Type: application/json

{
  "rate": 3
}

###
DELETE http://localhost:5000/api/grade/10/delete